### ISSUE TITLE
error in config.properties

### ISSUE THREAD

**Issue by 4ccr0z** [F-Locos/StarLoco---Game#4]
Hey,
I had a error when i launch .jar:
java.io.FileNotFoundException: Logs/Error/19-06-2018 - 21-37-02.log (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at org.starloco.locos.kernel.Main.main(Main.kt:66)
21:37:02.585 [main] INFO  org.starloco.locos.kernel.Main - You use Oracle Corporation with the version 1.8.0_171
21:37:02.588 [main] DEBUG org.starloco.locos.kernel.Main - Starting of the server : 19/06/2018 - 21:37:02
21:37:02.588 [main] DEBUG org.starloco.locos.kernel.Main - Current timestamp ms : 1529444222588
21:37:02.588 [main] DEBUG org.starloco.locos.kernel.Main - Current timestamp ns : 17321422563026521
21:37:02.590 [main] TRACE o.s.l.d.statics.StaticsDatabase - Reading database config
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.starloco.locos.database.statics.StaticsDatabase.initializeConnection(StaticsDatabase.java:69)
        at org.starloco.locos.database.Database.launchDatabase(Database.java:15)
        at org.starloco.locos.kernel.Main.start(Main.kt:83)
        at org.starloco.locos.kernel.Main.main(Main.kt:71)
Caused by: com.natpryce.konfig.Misconfiguration: console.debug property not found; searched:
 - CONSOLE_DEBUG in environment variables
 - console.debug in /root/t/Dof-Game/config.properties

        at com.natpryce.konfig.Configuration$get$1.invoke(konfig.kt:73)
        at com.natpryce.konfig.Configuration$get$1.invoke(konfig.kt:66)
        at com.natpryce.konfig.Configuration$DefaultImpls.getOrElse(konfig.kt:91)
        at com.natpryce.konfig.Override.getOrElse(konfig.kt:253)
        at com.natpryce.konfig.Configuration$DefaultImpls.get(konfig.kt:73)
        at com.natpryce.konfig.Override.get(konfig.kt:253)
        at org.starloco.locos.kernel.Config.<init>(Config.kt:15)
        at org.starloco.locos.kernel.Config.<clinit>(Config.kt:3)
        ... 4 more
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class org.starloco.locos.kernel.Config
        at org.starloco.locos.kernel.Main$main$1.run(Main.kt:42)

**Comment by 1150706** [comment]
console.debug = false
console.logs = false

add these two lines to your config.properties file

**Comment by F-Locos** [comment]
@4ccr0z is it fixed ?

**Comment by Docteur-Strange** [comment]
@F-Locos Hey, are you still working in this project ? Are there any updates incoming ? Debugs ?
